<?php

/**
 * @file
 * Install, update and uninstall functions for the Varbase Total Control Dashboard module.
 */

use Drupal\Core\Recipe\Recipe;
use Drupal\Core\Recipe\RecipeRunner;
use Vardot\Installer\ModuleInstallerFactory;

/**
 * Implements hook_install().
 */
function varbase_total_control_install() {

  // Processor for install: in varbase_total_control.info.yml file.
  ModuleInstallerFactory::installList('varbase_total_control');

  // Install optional configs.
  ModuleInstallerFactory::importConfigsFromScanedDirectory('varbase_total_control', '/^.*(settings.yml)$/i');

  // Grant role permissions via the default recipe.
  $default_recipe = Recipe::createFromDirectory(__DIR__ . '/recipes/default');
  RecipeRunner::processRecipe($default_recipe);

}

/**
 * Issue #3272301: Switch to use the Module Installer Factory.
 *
 * In the Varbase Total Control Dashboard module.
 */
function varbase_total_control_update_90001() {
  // Set the weight of the module after installation of list of modules.
  // To make sure that any hook or event subscriber worker after all used modules.
  ModuleInstallerFactory::setModuleWeightAfterInstallation('varbase_total_control');
}
